name: MiPrimerPlugin
version: 1.0
main: me.adelch.App
api-version: "1.21"
author: adelch
commands:
  tocar:
    description: Un comando de prueba para mi primer plugin.
    usage: /tocar
  zeus:
    description: Invoca un rayo.
    usage: /zeus
  minigun:
    description: Da una minigun al jugador. 
    usage: /minigun
  soltartodos:
    description: Suelta los objetos de la mano de todos los jugadores.
    usage: /soltartodos
  attackboost:
    description: Da un objeto con velocidad de ataque personalizada.
    usage: /attackboost